const categories = [
  { id: 'all', label: 'All calculators', icon: 'fa-border-all' },
  { id: 'ai', label: 'AI Toolkit', icon: 'fa-wand-magic-sparkles' },
  { id: 'finance', label: 'Finance', icon: 'fa-chart-pie' }, { id: 'health', label: 'Health', icon: 'fa-heart-pulse' },
  { id: 'math', label: 'Math', icon: 'fa-square-root-variable' }, { id: 'date', label: 'Date & time', icon: 'fa-calendar-days' },
  { id: 'units', label: 'Unit converter', icon: 'fa-ruler-combined' }, { id: 'engineering', label: 'Engineering', icon: 'fa-compass-drafting' },
  { id: 'home', label: 'Home', icon: 'fa-house-chimney' }, { id: 'auto', label: 'Automobile', icon: 'fa-car-side' }, { id: 'education', label: 'Education', icon: 'fa-graduation-cap' }, { id: 'utility', label: 'Utility tools', icon: 'fa-wand-magic-sparkles' }
];
const calculators = [
  {id:'tokenizer',name:'Tokenizer',desc:'Estimate tokens, context, and API cost',category:'ai',icon:'fa-cubes-stacked',color:'purple'},
  {id:'promptOptimizer',name:'Prompt Optimizer',desc:'Turn a rough request into a clear brief',category:'ai',icon:'fa-wand-magic-sparkles',color:'orange'},
  {id:'emi',name:'EMI Calculator',desc:'Plan a loan with clarity',category:'finance',icon:'fa-indian-rupee-sign',color:'purple',popular:true},
  {id:'sip',name:'SIP Calculator',desc:'See your money grow',category:'finance',icon:'fa-seedling',color:'green',popular:true},
  {id:'gst',name:'GST Calculator',desc:'Add or remove GST instantly',category:'finance',icon:'fa-receipt',color:'orange',popular:true},
  {id:'incomeTax',name:'Income Tax',desc:'Estimate your tax outgo',category:'finance',icon:'fa-file-invoice-dollar',color:'purple'},
  {id:'fd',name:'FD Calculator',desc:'Calculate maturity value',category:'finance',icon:'fa-building-columns',color:'orange'},
  {id:'discount',name:'Discount Calculator',desc:'Find your savings',category:'finance',icon:'fa-tags',color:'green'},
  {id:'bmi',name:'BMI Calculator',desc:'Check your body mass index',category:'health',icon:'fa-heart-pulse',color:'orange',popular:true},
  {id:'bmr',name:'Daily Calorie Need',desc:'Estimate your energy needs',category:'health',icon:'fa-fire-flame-curved',color:'purple'},
  {id:'water',name:'Water Intake',desc:'Your daily hydration goal',category:'health',icon:'fa-glass-water',color:'green'},
  {id:'idealWeight',name:'Ideal Weight',desc:'Healthy weight range',category:'health',icon:'fa-weight-scale',color:'orange'},
  {id:'percentage',name:'Percentage',desc:'Solve any percentage',category:'math',icon:'fa-percent',color:'purple',popular:true},
  {id:'average',name:'Average Calculator',desc:'Mean of a number set',category:'math',icon:'fa-chart-simple',color:'green'},
  {id:'scientific',name:'Scientific Calculator',desc:'Everyday arithmetic',category:'math',icon:'fa-calculator',color:'orange'},
  {id:'ratio',name:'Ratio Calculator',desc:'Simplify a ratio',category:'math',icon:'fa-divide',color:'purple'},
  {id:'age',name:'Age Calculator',desc:'Your exact age in detail',category:'date',icon:'fa-cake-candles',color:'purple',popular:true},
  {id:'dateDiff',name:'Date Difference',desc:'Count days between dates',category:'date',icon:'fa-calendar-week',color:'orange'},
  {id:'countdown',name:'Countdown Timer',desc:'Time until the big day',category:'date',icon:'fa-hourglass-half',color:'green'},
  {id:'businessDays',name:'Business Days',desc:'Working days between dates',category:'date',icon:'fa-briefcase',color:'purple'},
  {id:'converter',name:'Unit Converter',desc:'Length, weight, temperature & more',category:'units',icon:'fa-ruler-combined',color:'green',popular:true},
  {id:'temperature',name:'Temperature',desc:'°C, °F and Kelvin',category:'units',icon:'fa-temperature-half',color:'orange'},
  {id:'speed',name:'Speed Converter',desc:'km/h, mph, m/s, knots',category:'units',icon:'fa-gauge-high',color:'purple'},
  {id:'storage',name:'Data Storage',desc:'KB, MB, GB and TB',category:'units',icon:'fa-hard-drive',color:'green'},
  {id:'paint',name:'Paint Calculator',desc:'Estimate paint you need',category:'home',icon:'fa-paint-roller',color:'purple'},
  {id:'tile',name:'Tile Calculator',desc:'Plan your floor coverage',category:'home',icon:'fa-border-all',color:'orange'},
  {id:'fuel',name:'Fuel Cost',desc:'Calculate your trip cost',category:'auto',icon:'fa-gas-pump',color:'green'},
  {id:'mileage',name:'Fuel Mileage',desc:'Track your vehicle efficiency',category:'auto',icon:'fa-road',color:'purple'},
  {id:'gpa',name:'GPA Calculator',desc:'Calculate your GPA',category:'education',icon:'fa-graduation-cap',color:'orange'},
  {id:'attendance',name:'Attendance',desc:'Know classes you need',category:'education',icon:'fa-user-check',color:'green'},
  {id:'density',name:'Density Calculator',desc:'Mass, volume and density',category:'engineering',icon:'fa-cubes',color:'purple'},
  {id:'torque',name:'Torque Calculator',desc:'Force × lever distance',category:'engineering',icon:'fa-gear',color:'orange'},
  {id:'beamDeflection',name:'Beam Deflection',desc:'Deflection for a centre-loaded beam',category:'engineering',icon:'fa-ruler-horizontal',color:'green'},
  {id:'shaftPower',name:'Shaft Power',desc:'Power from torque and RPM',category:'engineering',icon:'fa-fan',color:'purple'},
  {id:'boltPreload',name:'Bolt Preload',desc:'Estimate clamp-load target',category:'engineering',icon:'fa-screwdriver-wrench',color:'orange'},
  {id:'beltDrive',name:'Belt Drive Ratio',desc:'Driver and driven pulley speed',category:'engineering',icon:'fa-rotate',color:'green'},
  {id:'springRate',name:'Spring Rate',desc:'Force and spring compression',category:'engineering',icon:'fa-compress',color:'purple'},
  {id:'heatTransfer',name:'Heat Transfer',desc:'Thermal power through a wall',category:'engineering',icon:'fa-temperature-arrow-up',color:'orange'},
  {id:'password',name:'Password Generator',desc:'Create a secure password',category:'utility',icon:'fa-key',color:'green'},
  {id:'random',name:'Random Number',desc:'Pick a number at random',category:'utility',icon:'fa-dice',color:'purple'}
];
let activeCategory = 'ai'; let favorites = JSON.parse(localStorage.getItem('calcverse-favorites') || '[]'); let recent = JSON.parse(localStorage.getItem('calcverse-recent') || '[]');
const $ = s => document.querySelector(s); const $$ = s => [...document.querySelectorAll(s)];
const titleCase = s => categories.find(c=>c.id===s)?.label || s;
const tokenModels = {
  'gpt-5': {label:'GPT-5', input:1.25, output:10, context:400000},
  'gpt-5-mini': {label:'GPT-5 mini', input:.25, output:2, context:400000},
  'gpt-4.1': {label:'GPT-4.1', input:2, output:8, context:1000000},
  'gpt-4.1-mini': {label:'GPT-4.1 mini', input:.4, output:1.6, context:1000000}
};
function iconClass(color){return `card-icon ${color}`}
function card(calc){ const favored=favorites.includes(calc.id); return `<article class="calc-card" data-id="${calc.id}" tabindex="0" role="button" aria-label="Open ${calc.name}"><button class="favorite-button ${favored?'favorited':''}" data-favorite="${calc.id}" aria-label="Favorite ${calc.name}"><i class="${favored?'fa-solid':'fa-regular'} fa-star"></i></button><span class="${iconClass(calc.color)}"><i class="fa-solid ${calc.icon}"></i></span><h3>${calc.name}</h3><p>${calc.desc}</p><i class="card-action fa-solid fa-arrow-up-right-from-square"></i></article>` }
function render(){
  $('#categoryNav').innerHTML = categories.filter(c=>c.id!=='all').map(c=>`<button class="category-link ${activeCategory===c.id?'selected':''}" data-category="${c.id}"><i class="fa-solid ${c.icon}"></i>${c.label}</button>`).join('');
  $('#overviewCategoryGrid').innerHTML = categories.filter(c=>c.id!=='all').map(c=>`<button class="category-overview-card ${activeCategory===c.id?'active':''}" data-category="${c.id}"><span class="category-overview-icon"><i class="fa-solid ${c.icon}"></i></span><span><strong>${c.label}</strong><small>${calculators.filter(x=>x.category===c.id).length} tools</small></span><i class="fa-solid fa-arrow-right"></i></button>`).join('');
  const q=$('#calculatorSearch').value.trim().toLowerCase(); const results=calculators.filter(c=>(activeCategory==='all'||c.category===activeCategory)&&(`${c.name} ${c.desc} ${c.category}`).toLowerCase().includes(q));
  $('#calculatorGrid').innerHTML=results.map(card).join(''); $('#activeCategoryName').textContent=activeCategory==='all'?'All calculators':titleCase(activeCategory); $('#resultCount').textContent=`${results.length} tools`; $('#emptyState').classList.toggle('hidden',results.length>0); $('#calculatorGrid').classList.toggle('hidden',!results.length);
  $('#searchHint').textContent=q?`${results.length} matching tool${results.length===1?'':'s'} found`:'Browse by category or search 50+ useful tools'; $('#favoriteCount').textContent=favorites.length;
  const recents=recent.map(id=>calculators.find(c=>c.id===id)).filter(Boolean); $('#recent').classList.toggle('hidden',!recents.length); $('#recentList').innerHTML=recents.map(c=>`<button class="recent-item" data-id="${c.id}"><i class="fa-solid ${c.icon}"></i>${c.name}</button>`).join('');
  bindCards();
}
function bindCards(){ $$('[data-id]').forEach(el=>el.addEventListener('click',e=>{if(!e.target.closest('[data-favorite]'))openCalculator(el.dataset.id)})); $$('[data-favorite]').forEach(el=>el.addEventListener('click',e=>{e.stopPropagation();toggleFavorite(el.dataset.favorite)})); $$('[data-category]').forEach(el=>el.addEventListener('click',()=>{activeCategory=el.dataset.category;render();$('#explore').scrollIntoView({behavior:'smooth',block:'start'});$('#sidebar').classList.remove('open')})); }
function toggleFavorite(id){favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];localStorage.setItem('calcverse-favorites',JSON.stringify(favorites));render();toast(favorites.includes(id)?'Added to favorites':'Removed from favorites')}
function openCalculator(id){ const calc=calculators.find(c=>c.id===id); if(!calc)return; recent=[id,...recent.filter(x=>x!==id)].slice(0,5);localStorage.setItem('calcverse-recent',JSON.stringify(recent));render();$('#modalTitle').textContent=calc.name;$('#modalCategory').textContent=titleCase(calc.category); $('#modalBody').innerHTML=forms[id] || `<p class="detail-note">This calculator is unavailable right now.</p>`;$('#calculatorModal').classList.remove('hidden');$('#modalBackdrop').classList.remove('hidden'); bindForm(id); }
function closeModal(){$('#calculatorModal').classList.add('hidden');$('#modalBackdrop').classList.add('hidden')}
const inField=(id,label,value,suffix='')=>`<div class="form-group"><label for="${id}">${label}</label><div class="input-wrap"><input id="${id}" type="number" min="0" step="any" placeholder="Enter ${label.toLowerCase()}"><span class="input-suffix">${suffix}</span></div></div>`;
const result=(items, two=false)=>`<div class="result-panel ${two?'two':''}">${items.map(([a,b])=>`<div><span>${a}</span><strong>${b}</strong></div>`).join('')}</div>`;
const forms={
 emi:`<div class="form-grid">${inField('loanAmount','Loan amount','2500000','₹')}${inField('interestRate','Interest rate','8.5','% p.a.')}${inField('loanYears','Loan tenure','20','years')}</div><button class="calculate-button" data-calc="emi">Calculate EMI</button><div id="calcResult"></div>`,
 sip:`<div class="form-grid">${inField('monthlyInvestment','Monthly investment','10000','₹')}${inField('sipReturn','Expected return','12','% p.a.')}${inField('sipYears','Investment duration','10','years')}</div><button class="calculate-button" data-calc="sip">Calculate returns</button><div id="calcResult"></div>`,
 gst:`<div class="tax-toggle"><button class="active" data-gst="add">Add GST</button><button data-gst="remove">Remove GST</button></div><div class="form-grid">${inField('gstAmount','Original amount','1000','₹')}<div class="form-group"><label for="gstRate">GST rate</label><div class="input-wrap"><select id="gstRate"><option>5</option><option>12</option><option selected>18</option><option>28</option></select><span class="input-suffix">%</span></div></div></div><button class="calculate-button" data-calc="gst">Calculate GST</button><div id="calcResult"></div>`,
 bmi:`<div class="form-grid">${inField('height','Height','170','cm')}${inField('weight','Weight','65','kg')}</div><button class="calculate-button" data-calc="bmi">Check BMI</button><div id="calcResult"></div>`,
 bmr:`<div class="form-grid">${inField('bmrAge','Age','28','years')}${inField('bmrWeight','Weight','65','kg')}${inField('bmrHeight','Height','170','cm')}<div class="form-group"><label for="sex">Biological sex</label><div class="input-wrap"><select id="sex"><option value="male">Male</option><option value="female">Female</option></select></div></div></div><button class="calculate-button" data-calc="bmr">Estimate calories</button><div id="calcResult"></div>`,
 water:`<div class="form-grid">${inField('waterWeight','Your weight','65','kg')}<div class="form-group"><label for="activity">Activity level</label><div class="input-wrap"><select id="activity"><option value="0">Low activity</option><option value="350" selected>Moderate activity</option><option value="700">High activity</option></select></div></div></div><button class="calculate-button" data-calc="water">Calculate intake</button><div id="calcResult"></div>`,
 percentage:`<div class="form-grid">${inField('part','What is','20','')}${inField('whole','Percent of','250','')}</div><button class="calculate-button" data-calc="percentage">Calculate percentage</button><div id="calcResult"></div>`,
 average:`<div class="form-grid"><div class="form-group full"><label for="numbers">Numbers (comma separated)</label><div class="input-wrap"><input id="numbers" type="text" placeholder="For example: 12, 18, 24"></div></div></div><button class="calculate-button" data-calc="average">Find average</button><div id="calcResult"></div>`,
 scientific:`<div class="form-grid"><div class="form-group full"><label for="expression">Expression</label><div class="input-wrap"><input id="expression" type="text" placeholder="For example: (25 * 8) + 14"></div></div></div><button class="calculate-button" data-calc="scientific">Calculate</button><div id="calcResult"></div><p class="detail-note">Supports +, minus, multiply, divide, brackets, decimals and powers (^).</p>`,
 age:`<div class="form-grid"><div class="form-group"><label for="birthDate">Date of birth</label><div class="input-wrap"><input id="birthDate" type="date"></div></div><div class="form-group"><label for="asOfDate">Calculate on</label><div class="input-wrap"><input id="asOfDate" type="date"></div></div></div><button class="calculate-button" data-calc="age">Calculate age</button><div id="calcResult"></div>`,
 dateDiff:`<div class="form-grid"><div class="form-group"><label for="startDate">Start date</label><div class="input-wrap"><input id="startDate" type="date"></div></div><div class="form-group"><label for="endDate">End date</label><div class="input-wrap"><input id="endDate" type="date"></div></div></div><button class="calculate-button" data-calc="dateDiff">Find difference</button><div id="calcResult"></div>`,
 converter:`<div class="form-grid"><div class="form-group full"><label for="unitType">Convert</label><div class="input-wrap"><select id="unitType"><option value="length">Length</option><option value="weight">Weight</option><option value="temperature">Temperature</option><option value="speed">Speed</option></select></div></div></div><div class="convert-row"><div class="form-group"><label for="fromValue">Value</label><div class="input-wrap"><input id="fromValue" type="number" placeholder="Enter value"></div><select id="fromUnit"></select></div><button class="swap-button" id="swapUnits" aria-label="Swap units"><i class="fa-solid fa-arrow-right-arrow-left"></i></button><div class="form-group"><label for="toValue">Result</label><div class="input-wrap"><input id="toValue" type="text" readonly></div><select id="toUnit"></select></div></div><div id="calcResult"></div>`,
 temperature:`<div class="convert-row"><div class="form-group"><label for="fromValue">Celsius</label><div class="input-wrap"><input id="fromValue" type="number" placeholder="Enter Celsius"></div></div><button class="swap-button" id="swapUnits"><i class="fa-solid fa-arrow-right-arrow-left"></i></button><div class="form-group"><label for="toValue">Fahrenheit</label><div class="input-wrap"><input id="toValue" type="text" readonly></div></div></div><div id="calcResult"></div>`,
 fuel:`<div class="form-grid">${inField('distance','Trip distance','350','km')}${inField('efficiency','Mileage','16','km/l')}${inField('fuelPrice','Fuel price','102','₹/l')}</div><button class="calculate-button" data-calc="fuel">Estimate trip cost</button><div id="calcResult"></div>`,
 paint:`<div class="form-grid">${inField('roomLength','Room length','15','ft')}${inField('roomWidth','Room width','12','ft')}${inField('paintCoats','Number of coats','2','')}</div><button class="calculate-button" data-calc="paint">Estimate paint</button><div id="calcResult"></div>`,
 gpa:`<div class="form-grid">${inField('gradePoints','Total grade points','34','')}${inField('credits','Total course credits','10','')}</div><button class="calculate-button" data-calc="gpa">Calculate GPA</button><div id="calcResult"></div>`,
 password:`<div class="form-grid">${inField('passwordLength','Password length','16','characters')}</div><button class="calculate-button" data-calc="password">Generate password</button><div id="calcResult"></div>`,
 random:`<div class="form-grid">${inField('randomMin','Minimum','1','')}${inField('randomMax','Maximum','100','')}</div><button class="calculate-button" data-calc="random">Generate number</button><div id="calcResult"></div>`,
 tokenizer:`<div class="form-grid"><div class="form-group full"><label for="tokenPrompt">Prompt or text</label><textarea id="tokenPrompt" rows="7" placeholder="Paste a prompt, document, message, or code here..."></textarea></div><div class="form-group"><label for="tokenModel">Model</label><div class="input-wrap"><select id="tokenModel"><option value="" selected disabled>Choose a model</option><option value="gpt-5">GPT-5</option><option value="gpt-5-mini">GPT-5 mini</option><option value="gpt-4.1">GPT-4.1</option><option value="gpt-4.1-mini">GPT-4.1 mini</option></select></div></div>${inField('tokenOutput','Planned output','', 'tokens')}</div><button class="calculate-button" data-calc="tokenizer">Analyze prompt</button><div id="calcResult"></div><p class="detail-note">Token counts are local estimates. Exact tokenization and billed usage can vary by model, tools, and API settings.</p>`,
 promptOptimizer:`<div class="form-grid"><div class="form-group full"><label for="optimizerPrompt">Your draft prompt</label><textarea id="optimizerPrompt" rows="8" placeholder="Paste the prompt you want to improve..."></textarea></div></div><button class="calculate-button" data-calc="promptOptimizer">Optimize prompt</button><div id="calcResult"></div><p class="detail-note">Creates a clearer, reusable prompt structure without sending your text anywhere.</p>`,
 beamDeflection:`<div class="form-grid">${inField('beamForce','Centre load','', 'N')}${inField('beamLength','Beam span','', 'm')}${inField('beamElasticity','Youngs modulus','', 'GPa')}${inField('beamInertia','Second moment of area','', 'm4')}</div><button class="calculate-button" data-calc="beamDeflection">Calculate deflection</button><div id="calcResult"></div>`,
 shaftPower:`<div class="form-grid">${inField('shaftTorque','Shaft torque','', 'Nm')}${inField('shaftRpm','Rotational speed','', 'RPM')}</div><button class="calculate-button" data-calc="shaftPower">Calculate power</button><div id="calcResult"></div>`,
 boltPreload:`<div class="form-grid">${inField('boltProof','Bolt proof load','', 'N')}${inField('boltFactor','Preload factor','', '')}</div><button class="calculate-button" data-calc="boltPreload">Estimate preload</button><div id="calcResult"></div>`,
 beltDrive:`<div class="form-grid">${inField('driverDiameter','Driver pulley','', 'mm')}${inField('drivenDiameter','Driven pulley','', 'mm')}${inField('driverRpm','Driver speed','', 'RPM')}</div><button class="calculate-button" data-calc="beltDrive">Calculate ratio</button><div id="calcResult"></div>`,
 springRate:`<div class="form-grid">${inField('springForce','Applied force','', 'N')}${inField('springDeflection','Spring compression','', 'mm')}</div><button class="calculate-button" data-calc="springRate">Calculate spring rate</button><div id="calcResult"></div>`,
 heatTransfer:`<div class="form-grid">${inField('thermalConductivity','Thermal conductivity','', 'W/mK')}${inField('wallArea','Wall area','', 'm2')}${inField('temperatureDifference','Temperature difference','', 'K')}${inField('wallThickness','Wall thickness','', 'm')}</div><button class="calculate-button" data-calc="heatTransfer">Calculate heat flow</button><div id="calcResult"></div>`,
 incomeTax:`<div class="form-grid">${inField('taxIncome','Annual taxable income','','INR')}<div class="form-group"><label for="taxRegime">Tax regime</label><div class="input-wrap"><select id="taxRegime"><option value="new">New regime (AY 2026-27)</option><option value="old">Old regime</option></select></div></div></div><button class="calculate-button" data-calc="incomeTax">Estimate tax</button><div id="calcResult"></div><p class="detail-note">Indicative resident-individual estimate. Deductions, surcharge, capital gains, and marginal relief are not included.</p>`,
 fd:`<div class="form-grid">${inField('fdDeposit','Deposit amount','500000','INR')}${inField('fdRate','Interest rate','7.1','% p.a.')}${inField('fdYears','Term','5','years')}<div class="form-group"><label for="fdFrequency">Compounding</label><div class="input-wrap"><select id="fdFrequency"><option value="1">Yearly</option><option value="4" selected>Quarterly</option><option value="12">Monthly</option></select></div></div></div><button class="calculate-button" data-calc="fd">Calculate maturity</button><div id="calcResult"></div>`,
 discount:`<div class="form-grid">${inField('originalPrice','Original price','2500','INR')}${inField('discountRate','Discount','20','%')}</div><button class="calculate-button" data-calc="discount">Calculate savings</button><div id="calcResult"></div>`,
 idealWeight:`<div class="form-grid">${inField('idealHeight','Height','170','cm')}<div class="form-group"><label for="idealSex">Biological sex</label><div class="input-wrap"><select id="idealSex"><option value="male">Male</option><option value="female">Female</option></select></div></div></div><button class="calculate-button" data-calc="idealWeight">Find ideal weight</button><div id="calcResult"></div>`,
 ratio:`<div class="form-grid">${inField('ratioA','First value','24','')}${inField('ratioB','Second value','36','')}</div><button class="calculate-button" data-calc="ratio">Simplify ratio</button><div id="calcResult"></div>`,
 countdown:`<div class="form-grid"><div class="form-group full"><label for="countdownDate">Target date & time</label><div class="input-wrap"><input id="countdownDate" type="datetime-local"></div></div></div><button class="calculate-button" data-calc="countdown">Calculate countdown</button><div id="calcResult"></div>`,
 businessDays:`<div class="form-grid"><div class="form-group"><label for="businessStart">Start date</label><div class="input-wrap"><input id="businessStart" type="date"></div></div><div class="form-group"><label for="businessEnd">End date</label><div class="input-wrap"><input id="businessEnd" type="date"></div></div></div><button class="calculate-button" data-calc="businessDays">Count working days</button><div id="calcResult"></div><p class="detail-note">Weekends are excluded. Public holidays are not included.</p>`,
 speed:`<div class="form-grid">${inField('speedValue','Speed','100','km/h')}<div class="form-group"><label for="speedUnit">Convert to</label><div class="input-wrap"><select id="speedUnit"><option value="mph">mph</option><option value="ms">m/s</option><option value="knot">knots</option></select></div></div></div><button class="calculate-button" data-calc="speed">Convert speed</button><div id="calcResult"></div>`,
 storage:`<div class="form-grid">${inField('storageValue','Storage amount','5','GB')}<div class="form-group"><label for="storageUnit">Convert to</label><div class="input-wrap"><select id="storageUnit"><option value="KB">KB</option><option value="MB">MB</option><option value="TB">TB</option></select></div></div></div><button class="calculate-button" data-calc="storage">Convert storage</button><div id="calcResult"></div>`,
 tile:`<div class="form-grid">${inField('floorLength','Floor length','15','ft')}${inField('floorWidth','Floor width','12','ft')}${inField('tileSize','Square tile side','24','inches')}${inField('tileWaste','Extra for cuts','10','%')}</div><button class="calculate-button" data-calc="tile">Estimate tiles</button><div id="calcResult"></div>`,
 mileage:`<div class="form-grid">${inField('mileageDistance','Distance travelled','450','km')}${inField('mileageFuel','Fuel used','30','litres')}</div><button class="calculate-button" data-calc="mileage">Calculate mileage</button><div id="calcResult"></div>`,
 attendance:`<div class="form-grid">${inField('classesHeld','Classes held','80','')}${inField('classesAttended','Classes attended','60','')}${inField('attendanceTarget','Target attendance','75','%')}</div><button class="calculate-button" data-calc="attendance">Check attendance</button><div id="calcResult"></div>`,
 density:`<div class="form-grid">${inField('densityMass','Mass','250','kg')}${inField('densityVolume','Volume','0.1','m3')}</div><button class="calculate-button" data-calc="density">Calculate density</button><div id="calcResult"></div>`,
 torque:`<div class="form-grid">${inField('torqueForce','Force','250','N')}${inField('torqueLength','Lever distance','0.4','m')}</div><button class="calculate-button" data-calc="torque">Calculate torque</button><div id="calcResult"></div>`
};
const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n);
function val(id){return Number($(`#${id}`)?.value)||0}
function escapeHtml(text){return String(text).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
function bindResultActions(kind,text){const copy=$(`#copy${kind[0].toUpperCase()+kind.slice(1)}${kind==='token'?'Results':'Prompt'}`),download=$(`#download${kind[0].toUpperCase()+kind.slice(1)}${kind==='token'?'Results':'Prompt'}`);copy?.addEventListener('click',async()=>{await navigator.clipboard.writeText(text);toast('Copied to clipboard')});download?.addEventListener('click',()=>{const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([text],{type:'text/plain'}));link.download=`${kind}-results.txt`;link.click();URL.revokeObjectURL(link.href)})}
function bindForm(id){
 if($('[data-calc]'))$('[data-calc]').addEventListener('click',()=>calculate(id));
 if(id==='gst')$$('[data-gst]').forEach(b=>b.addEventListener('click',()=>{$$('[data-gst]').forEach(x=>x.classList.remove('active'));b.classList.add('active')}));
 if(id==='converter'){ setupConverter(); } if(id==='temperature'){ const update=()=>{$('#toValue').value=(val('fromValue')*9/5+32).toFixed(2)+' °F'};$('#fromValue').addEventListener('input',update);update(); }
 if(id==='tokenizer'){['tokenPrompt','tokenModel','tokenOutput'].forEach(field=>document.querySelector(`#${field}`)?.addEventListener('input',()=>calculate('tokenizer')))}
}
function calculate(id){let out='';
 if(id==='emi'){const P=val('loanAmount'),r=val('interestRate')/1200,n=val('loanYears')*12,emi=r?P*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1):P/n,total=emi*n;out=result([['Monthly EMI',money(emi)],['Total interest',money(total-P)],['Total payment',money(total)]])}
 if(id==='sip'){const p=val('monthlyInvestment'),r=val('sipReturn')/1200,n=val('sipYears')*12,fv=p*((Math.pow(1+r,n)-1)/r)*(1+r),invested=p*n;out=result([['Future value',money(fv)],['Invested amount',money(invested)],['Wealth gained',money(fv-invested)]])}
 if(id==='gst'){const amount=val('gstAmount'),rate=val('gstRate')/100,add=$('[data-gst].active')?.dataset.gst==='add',base=add?amount:amount/(1+rate),tax=base*rate,total=base+tax;out=result([['Base amount',money(base)],['GST amount',money(tax)],['Final amount',money(total)]])}
 if(id==='bmi'){const h=val('height')/100,w=val('weight'),b=w/(h*h),label=b<18.5?'Underweight':b<25?'Healthy range':b<30?'Overweight':'Obesity';out=result([['Your BMI',b.toFixed(1)],['Category',label]],true)+`<p class="detail-note">A BMI between 18.5 and 24.9 is generally considered within the healthy range.</p>`}
 if(id==='bmr'){const b=10*val('bmrWeight')+6.25*val('bmrHeight')-5*val('bmrAge')+($('#sex').value==='male'?5:-161);out=result([['Basal metabolic rate',Math.round(b)+' kcal'],['Moderate activity',Math.round(b*1.55)+' kcal/day']],true)}
 if(id==='water'){const ml=val('waterWeight')*35+Number($('#activity').value);out=result([['Daily goal',(ml/1000).toFixed(1)+' litres'],['Glasses of water',Math.round(ml/250)+' glasses']],true)}
 if(id==='percentage'){const p=val('part'),w=val('whole'),pct=w?p/w*100:0;out=result([['Result',pct.toFixed(2)+'%'],['In words',`${p} is ${pct.toFixed(2)}% of ${w}`]],true)}
 if(id==='average'){const nums=$('#numbers').value.split(',').map(Number).filter(n=>!isNaN(n));const avg=nums.reduce((a,b)=>a+b,0)/(nums.length||1);out=result([['Average',avg.toFixed(2)],['Numbers used',nums.length]],true)}
 if(id==='scientific'){try{const x=$('#expression').value.replace(/\^/g,'**');if(!/^[0-9+\-*/().\s*]+$/.test(x))throw Error();out=result([['Answer',Function(`"use strict";return (${x})`)()]],true)}catch{out=`<p class="detail-note">Enter a valid numeric expression.</p>`}}
 if(id==='age'){const birth=new Date($('#birthDate').value),now=new Date($('#asOfDate').value);let y=now.getFullYear()-birth.getFullYear(),m=now.getMonth()-birth.getMonth(),d=now.getDate()-birth.getDate();if(d<0){m--;d+=new Date(now.getFullYear(),now.getMonth(),0).getDate()}if(m<0){y--;m+=12}out=result([['Years',y],['Months',m],['Days',d]])}
 if(id==='dateDiff'){const diff=Math.abs(new Date($('#endDate').value)-new Date($('#startDate').value))/86400000;out=result([['Days between',Math.round(diff)],['Weeks',(diff/7).toFixed(1)]],true)}
 if(id==='fuel'){const litres=val('distance')/val('efficiency'),cost=litres*val('fuelPrice');out=result([['Fuel needed',litres.toFixed(1)+' L'],['Trip cost',money(cost)],['Cost per km',money(cost/val('distance'))]])}
 if(id==='paint'){const area=val('roomLength')*val('roomWidth'),litres=area*val('paintCoats')/100;out=result([['Wall area',area+' sq ft'],['Paint required',litres.toFixed(1)+' L']],true)}
 if(id==='gpa'){out=result([['Your GPA',(val('gradePoints')/val('credits')).toFixed(2)]],true)}
 if(id==='password'){const chars='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%&*';let p='';for(let i=0;i<val('passwordLength');i++)p+=chars[Math.floor(Math.random()*chars.length)];out=result([['New password',p]],true)}
 if(id==='random'){const min=val('randomMin'),max=val('randomMax');out=result([['Random number',Math.floor(Math.random()*(max-min+1))+min]],true)}
 if(id==='tokenizer'){const prompt=$('#tokenPrompt').value.trim(),model=tokenModels[$('#tokenModel').value];if(!prompt||!model){out=`<p class="detail-note">Paste text and choose a model to see token, context, and cost estimates.</p>`}else{const chunks=prompt.match(/[A-Za-z]+(?:'[A-Za-z]+)?|\d+(?:\.\d+)?|[^\w\s]/g)||[];const tokens=chunks.reduce((sum,chunk)=>sum+( /^[A-Za-z0-9]/.test(chunk)?Math.max(1,Math.ceil(chunk.length/4)):1),0);const words=(prompt.match(/\S+/g)||[]).length,characters=prompt.length,output=val('tokenOutput'),inputCost=tokens/1000000*model.input,outputCost=output/1000000*model.output,remaining=Math.max(0,model.context-tokens-output),reading=words?Math.max(1,Math.ceil(words/200)):0;const visualization=chunks.slice(0,140).map((chunk,i)=>`<span class="token-chip token-${i%5}">${escapeHtml(chunk)}</span>`).join('');out=result([['Total tokens',tokens.toLocaleString()],['Input cost','$'+inputCost.toFixed(6)],['Output cost','$'+outputCost.toFixed(6)],['Total API cost','$'+(inputCost+outputCost).toFixed(6)],['Word count',words.toLocaleString()],['Characters',characters.toLocaleString()],['Reading time',reading+' min'],['Context remaining',remaining.toLocaleString()]])+`<div class="token-meta"><span>${model.label} · ${model.context.toLocaleString()} token context</span><span>Planned output: ${output.toLocaleString()} tokens</span></div><div class="token-visualizer"><div class="visualizer-head"><strong>Token visualizer</strong><span>${chunks.length>140?'First 140 pieces shown':''}</span></div><div class="token-stream">${visualization||'<span class="detail-note">No token pieces found.</span>'}</div></div><div class="result-actions"><button class="text-button" id="copyTokenResults">Copy results</button><button class="text-button" id="downloadTokenResults">Download results</button></div>`;setTimeout(()=>bindResultActions('token',`Model: ${model.label}\nTokens: ${tokens}\nInput cost: $${inputCost.toFixed(6)}\nOutput cost: $${outputCost.toFixed(6)}\nTotal API cost: $${(inputCost+outputCost).toFixed(6)}\nWords: ${words}\nCharacters: ${characters}\nReading time: ${reading} min\nRemaining context: ${remaining}`),0)}}
 if(id==='promptOptimizer'){const draft=$('#optimizerPrompt').value.trim();if(!draft){out=`<p class="detail-note">Paste a draft prompt to generate a clearer, structured version.</p>`}else{const optimized=`ROLE\nYou are a domain expert who is accurate, practical, and concise.\n\nOBJECTIVE\n${draft}\n\nCONTEXT\nUse only the information supplied. State assumptions before relying on them.\n\nREQUIREMENTS\n- Address the request directly.\n- Use clear, plain language.\n- Separate facts, assumptions, and recommendations.\n- Ask a focused question only when essential information is missing.\n\nOUTPUT FORMAT\nStart with the answer. Then provide concise supporting steps or a table when it improves clarity.\n\nQUALITY CHECK\nBefore answering, verify calculations, dates, units, and constraints.`;out=`<div class="optimizer-result"><div class="visualizer-head"><strong>Optimized prompt</strong><span>Ready to copy</span></div><pre id="optimizedPrompt">${escapeHtml(optimized)}</pre><div class="result-actions"><button class="text-button" id="copyOptimizedPrompt">Copy prompt</button><button class="text-button" id="downloadOptimizedPrompt">Download prompt</button></div></div>`;setTimeout(()=>bindResultActions('optimized',optimized),0)}}
 if(id==='beamDeflection'){const f=val('beamForce'),l=val('beamLength'),e=val('beamElasticity')*1e9,i=val('beamInertia'),deflection=f*l**3/(48*e*i);out=result([['Maximum deflection',(deflection*1000).toFixed(3)+' mm'],['Beam span',l+' m'],['Centre load',f+' N']])}
 if(id==='shaftPower'){const torque=val('shaftTorque'),rpm=val('shaftRpm'),watts=2*Math.PI*rpm*torque/60;out=result([['Shaft power',(watts/1000).toFixed(3)+' kW'],['Torque',torque+' Nm'],['Speed',rpm+' RPM']])}
 if(id==='boltPreload'){const proof=val('boltProof'),factor=val('boltFactor');out=result([['Recommended preload',(proof*factor).toFixed(0)+' N'],['Proof load',proof+' N'],['Applied factor',factor]])}
 if(id==='beltDrive'){const driver=val('driverDiameter'),driven=val('drivenDiameter'),rpm=val('driverRpm'),ratio=driver/driven;out=result([['Speed ratio',ratio.toFixed(3)+': 1'],['Driven speed',(rpm*ratio).toFixed(1)+' RPM'],['Driver speed',rpm+' RPM']])}
 if(id==='springRate'){const force=val('springForce'),compression=val('springDeflection');out=result([['Spring rate',(force/compression).toFixed(3)+' N/mm'],['Applied force',force+' N'],['Compression',compression+' mm']])}
 if(id==='heatTransfer'){const q=val('thermalConductivity')*val('wallArea')*val('temperatureDifference')/val('wallThickness');out=result([['Heat flow',(q/1000).toFixed(3)+' kW'],['Heat flow',q.toFixed(1)+' W'],['Temperature difference',val('temperatureDifference')+' K']])}
 if(id==='incomeTax'){const income=val('taxIncome'),regime=$('#taxRegime').value;if(!income){out=`<p class="detail-note">Enter your annual taxable income to receive an estimate.</p>`}else{const slabs=regime==='new'?[[400000,0],[800000,.05],[1200000,.10],[1600000,.15],[2000000,.20],[2400000,.25],[Infinity,.30]]:[[250000,0],[500000,.05],[1000000,.20],[Infinity,.30]];let previous=0,slabTax=0;for(const [limit,rate] of slabs){const portion=Math.max(0,Math.min(income,limit)-previous);slabTax+=portion*rate;previous=limit;if(income<=limit)break}const rebateLimit=regime==='new'?1200000:500000;const rebateCap=regime==='new'?60000:12500;const rebate=income<=rebateLimit?Math.min(slabTax,rebateCap):0;const tax=Math.max(0,slabTax-rebate),cess=tax*.04;out=result([['Slab tax',money(slabTax)],['87A rebate',money(rebate)],['Income tax',money(tax)],['Health & education cess',money(cess)],['Estimated annual total',money(tax+cess)]])+`<p class="detail-note">${rebate?`A ${money(rebate)} Section 87A rebate applies under the ${regime==='new'?'new':'old'} regime for this income.`:'No Section 87A rebate applies at this income.'}</p>`}}
 if(id==='fd'){const p=val('fdDeposit'),n=val('fdFrequency'),maturity=p*Math.pow(1+val('fdRate')/100/n,n*val('fdYears'));out=result([['Maturity amount',money(maturity)],['Interest earned',money(maturity-p)],['Principal',money(p)]])}
 if(id==='discount'){const price=val('originalPrice'),saving=price*val('discountRate')/100;out=result([['You save',money(saving)],['Sale price',money(price-saving)]],true)}
 if(id==='idealWeight'){const inches=val('idealHeight')/2.54,base=$('#idealSex').value==='male'?50:45.5,ideal=base+2.3*(inches-60);out=result([['Estimated ideal weight',ideal.toFixed(1)+' kg'],['Healthy reference range',(ideal-5).toFixed(1)+' - '+(ideal+5).toFixed(1)+' kg']],true)}
 if(id==='ratio'){let a=Math.abs(Math.round(val('ratioA'))),b=Math.abs(Math.round(val('ratioB')));const gcd=(x,y)=>y?gcd(y,x%y):x||1;const divisor=gcd(a,b);out=result([['Simplified ratio',`${a/divisor} : ${b/divisor}`],['Common divisor',divisor]],true)}
 if(id==='countdown'){const ms=new Date($('#countdownDate').value)-Date.now(),total=Math.max(0,Math.floor(ms/1000)),days=Math.floor(total/86400),hours=Math.floor(total%86400/3600),minutes=Math.floor(total%3600/60);out=result([['Days',days],['Hours',hours],['Minutes',minutes]])}
 if(id==='businessDays'){let start=new Date($('#businessStart').value+'T00:00:00'),end=new Date($('#businessEnd').value+'T00:00:00'),days=0;while(start<=end){if(start.getDay()!==0&&start.getDay()!==6)days++;start.setDate(start.getDate()+1)}out=result([['Business days',days],['Calendar days',Math.round((end-new Date($('#businessStart').value+'T00:00:00'))/86400000)+1]],true)}
 if(id==='speed'){const kph=val('speedValue'),unit=$('#speedUnit').value,value=unit==='mph'?kph/1.609344:unit==='ms'?kph/3.6:kph/1.852;out=result([['Converted speed',value.toFixed(2)+' '+(unit==='ms'?'m/s':unit)]],true)}
 if(id==='storage'){const gb=val('storageValue'),unit=$('#storageUnit').value,value=unit==='KB'?gb*1024*1024:unit==='MB'?gb*1024:gb/1024;out=result([['Converted storage',Number(value.toFixed(4)).toLocaleString()+' '+unit]],true)}
 if(id==='tile'){const floor=val('floorLength')*val('floorWidth'),tile=Math.pow(val('tileSize')/12,2),count=Math.ceil(floor/tile*(1+val('tileWaste')/100));out=result([['Tiles required',count],['Floor area',floor+' sq ft'],['Including extra',val('tileWaste')+'%']])}
 if(id==='mileage'){const mileage=val('mileageDistance')/val('mileageFuel');out=result([['Fuel mileage',mileage.toFixed(2)+' km/l'],['Fuel per 100 km',(100/mileage).toFixed(2)+' L']],true)}
 if(id==='attendance'){const held=val('classesHeld'),attended=val('classesAttended'),target=val('attendanceTarget')/100,current=held?attended/held:0,needed=Math.max(0,Math.ceil((target*held-attended)/(1-target)));out=result([['Current attendance',(current*100).toFixed(1)+'%'],[current>=target?'Target status':'Classes needed',current>=target?'On track':needed+' more'],['Target',val('attendanceTarget')+'%']])}
 if(id==='density'){const d=val('densityMass')/val('densityVolume');out=result([['Density',d.toFixed(2)+' kg/m3'],['Mass',val('densityMass')+' kg'],['Volume',val('densityVolume')+' m3']])}
 if(id==='torque'){const t=val('torqueForce')*val('torqueLength');out=result([['Torque',t.toFixed(2)+' Nm'],['Force',val('torqueForce')+' N'],['Lever distance',val('torqueLength')+' m']])}
 $('#calcResult').innerHTML=out;
}
const unitSets={length:{Meter:1,Kilometer:1000,Centimeter:.01,Inch:.0254,Foot:.3048,Mile:1609.344},weight:{Kilogram:1,Gram:.001,Pound:.453592,Ounce:.0283495},speed:{'km/h':1,mph:1.609344,'m/s':3.6,Knot:1.852},temperature:{Celsius:'c',Fahrenheit:'f',Kelvin:'k'}};
function setupConverter(){const type=$('#unitType'),from=$('#fromUnit'),to=$('#toUnit');const populate=()=>{const units=Object.keys(unitSets[type.value]);from.innerHTML=units.map(u=>`<option>${u}</option>`).join('');to.innerHTML=units.map(u=>`<option ${u===units[1]?'selected':''}>${u}</option>`).join('');convert()};const convert=()=>{let n=val('fromValue'),v=type.value,a=from.value,b=to.value,x;if(v==='temperature'){const c=a==='Celsius'?n:a==='Fahrenheit'?(n-32)*5/9:n-273.15;x=b==='Celsius'?c:b==='Fahrenheit'?c*9/5+32:c+273.15}else x=n*unitSets[v][a]/unitSets[v][b];$('#toValue').value=Number(x.toFixed(6)).toLocaleString()};type.addEventListener('change',populate);[from,to,$('#fromValue')].forEach(e=>e.addEventListener('input',convert));$('#swapUnits').addEventListener('click',()=>{[from.value,to.value]=[to.value,from.value];convert()});populate()}
function toast(message){const t=$('#toast');t.textContent=message;t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),1800)}
$('#calculatorSearch').addEventListener('input',render);$('#themeToggle').addEventListener('click',()=>{document.body.classList.toggle('dark');localStorage.setItem('calcverse-theme',document.body.classList.contains('dark')?'dark':'light');$('#themeToggle i').className=document.body.classList.contains('dark')?'fa-solid fa-sun':'fa-regular fa-moon'}); if(localStorage.getItem('calcverse-theme')==='dark')$('#themeToggle').click();
$('#modalClose').addEventListener('click',closeModal);$('#modalBackdrop').addEventListener('click',closeModal);$('#menuButton').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));$('#clearRecent').addEventListener('click',()=>{recent=[];localStorage.removeItem('calcverse-recent');render()});document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#calculatorSearch').focus()}if(e.key==='Escape')closeModal()});
render();
